### ISSUE TITLE
Can not run  VehicleDetectionModel.py 

### ISSUE THREAD

**Issue by soufianelb** [mohamedameen93/Vehicle-Detection-and-Tracking#1]
Hello everyone,

I have an issue. I can't run  VehicleDetectionModel.py

i got some error's  when i try to execute  VehicleDetectionModel.py

error;
Vehicle-Detection-and-Tracking\VehicleDetectionModel.py in <module>
    178
    179 veh_img = cv2.cvtColor(cv2.imread(cars[np.random.randint(0, len(cars))]), cv2.COLOR_BGR2RGB)
--> 180 _, veh_dst = get_hog_features(veh_img[:,:,2], 9, 8, 8, vis=True, feature_vec=True)
    181 nonveh_img = cv2.cvtColor(cv2.imread(notcars[np.random.randint(0, len(notcars))]), cv2.COLOR_BGR2RGB)
    182 _, nonveh_dst = get_hog_features(nonveh_img[:,:,2], 9, 8, 8, vis=True, feature_vec=True)

~\Projects\Vehicle-Detection-and-Tracking\VehicleDetectionModel.py in get_hog_features(img, orient, pix_per_cell, cell_per_block, vis, feature_vec)
    159     """
    160     if vis == True:
--> 161         features, hog_image = hog(img, orientations=orient, 
    162                                   pixels_per_cell=(pix_per_cell, pix_per_cell),
    163                                   cells_per_block=(cell_per_block, cell_per_block),

TypeError: hog() got an unexpected keyword argument 'visualise'

**Comment by mohamedameen-io** [comment]
Hi, if you're using any scikit-image version newer than 0.13 you have to change "visualise" to "visualize". Lines #165 and #172.
